#!/bin/sh
#   ______  _     _  ______   _______  ______   _______  _  _  _
#  / _____)(_)   (_)(_____ \ (_______)(_____ \ (_______)(_)(_)(_)
# ( (____   _     _  _____) ) _____    _____) ) _______  _  _  _
#  \____ \ | |   | ||  __  / |  ___)  |  __  / |  ___  || || || |
#  _____) )| |___| || |  \ \ | |      | |  \ \ | |   | || || || |
# (______/  \_____/ |_|   |_||_|      |_|   |_||_|   |_| \_____/
# Surfraw - Shell Users' Revolutionary Front Rage Against the Web
#           https://surfraw.alioth.debian.org
#             _   _     _      _         
#  __ _  ___ | |_| |__ | | ___| |_ _   _ 
# / _` |/ _ \| __| '_ \| |/ _ \ __| | | |
#| (_| | (_) | |_| |_) | |  __/ |_| |_| |
# \__, |\___/ \__|_.__/|_|\___|\__|\__,_|
# |___/                                  
#       https://www.youtube.com/user/gotbletu
#       https://twitter.com/gotbletu
#       https://plus.google.com/+gotbletu
#       https://github.com/gotbletu
#       gotbleu@gmail.com
#
# DATE: Tue Nov 06 2012
#
# DESC: Elvi to search epguides
# elvis: epguides	-- Search epguides for TV Show air dates (www.epguides.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search epguides (www.epguides.com) for videos
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.google.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.google.com/search?hl=en&q=allintitle%3A&q=site%3Aepguides.com&q=${escaped_args}&btnG=Search"
fi
