#!/bin/sh
#
# AUTHOR: gotbletu (https://twitter.com/gotbletu)
#
# DATE: Fri July 12, 2013
#
# DESC: Elvi to search F-droid
# elvis: fdroid		-- Search F-Droid for open source android apps (https://f-droid.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search fdroid (https://f-droid.org) for open source android apps
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://f-droid.org"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://f-droid.org/repository/browse/?fdfilter=${escaped_args}"
fi
