#!/bin/sh
#
# AUTHOR: gotbletu (https://twitter.com/gotbletu)
#
# DATE: Thu June 06, 2013
#
# DESC: Elvi to search kickasstorrents
# elvis: kickasstorrent	-- Search kickasstorrent for torrents (www.kat.ph)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search kickasstorrents (www.kat.ph) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.kat.ph"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://kat.ph/usearch/${escaped_args}"
fi
