#!/bin/sh
#   ______  _     _  ______   _______  ______   _______  _  _  _
#  / _____)(_)   (_)(_____ \ (_______)(_____ \ (_______)(_)(_)(_)
# ( (____   _     _  _____) ) _____    _____) ) _______  _  _  _
#  \____ \ | |   | ||  __  / |  ___)  |  __  / |  ___  || || || |
#  _____) )| |___| || |  \ \ | |      | |  \ \ | |   | || || || |
# (______/  \_____/ |_|   |_||_|      |_|   |_||_|   |_| \_____/
# Surfraw - Shell Users' Revolutionary Front Rage Against the Web
#           https://surfraw.alioth.debian.org
#             _   _     _      _         
#  __ _  ___ | |_| |__ | | ___| |_ _   _ 
# / _` |/ _ \| __| '_ \| |/ _ \ __| | | |
#| (_| | (_) | |_| |_) | |  __/ |_| |_| |
# \__, |\___/ \__|_.__/|_|\___|\__|\__,_|
# |___/                                  
#       https://www.youtube.com/user/gotbletu
#       https://twitter.com/gotbletu
#       https://plus.google.com/+gotbletu
#       https://github.com/gotbletu
#       gotbleu@gmail.com
#
# DATE: Thu Jan 17 2013
#
# DESC: Elvi to search nzbindex
# elvis: nzbindex	-- Search nzbindex for NZB (www.nzbindex.nl)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search nzbindex (www.nzbindex.nl) for NZB
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.google.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.nzbindex.nl/search/?q=${escaped_args}&age=&max=250&sort=agedesc&minsize=50&maxsize=&dq=&poster=&nfo=&hidecross=1&complete=1&hidespam=0&hidespam=1&more=1"
fi
