#!/bin/sh
#
# AUTHOR: gotbletu ( https://twitter.com/gotbletu )
#
# DATE: Sun August 09, 2015
#
# DESC: Elvi to search locally listed items for sell or trade
# elvis: offerupnow	-- Search locally listed items for sell or trade (https://offerupnow.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search locally listed items for sell or trade (https://offerupnow.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://offerupnow.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://offerupnow.com/search/?q=${escaped_args}"
fi
