#!/bin/sh
#
# AUTHOR: gotbletu (https://twitter.com/gotbletu)
#
# DATE: Sat Nov 17 2012
#
# DESC: Elvi to search torrentz
# elvis: torrentz	-- Search Torrentz for torrents (www.torrentz.eu)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search torrentz (www.torrentz.eu) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.torrentz.eu"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://torrentz.eu/search?f=${escaped_args}"
fi
