#!/bin/bash
#	http://bleachbit.sourceforge.net/documentation/command-line
#	dont delete pidgin, vim, transmission, thumbnails, bash, system, deep
# cdusr/bin/
bleachbit -c \
adobe_reader.cache \
adobe_reader.mru \
adobe_reader.tmp \
amsn.cache \
amsn.chat_logs \
amule.logs \
amule.tmp \
apt.autoclean \
apt.autoremove \
apt.clean \
apt.package_lists \
audacious.cache \
audacious.log \
audacious.mru \
beagle.cache \
beagle.index \
beagle.logs \
chromium.cache \
chromium.cookies \
chromium.current_session \
chromium.dom \
chromium.form_history \
chromium.history \
chromium.passwords \
chromium.search_engines \
chromium.vacuum \
d4x.history \
easytag.history \
easytag.logs \
elinks.history \
emesene.cache \
emesene.logs \
epiphany.cache \
epiphany.cookies \
epiphany.passwords \
epiphany.places \
evolution.cache \
exaile.cache \
exaile.downloaded_podcasts \
exaile.log \
filezilla.mru \
firefox.cache \
firefox.cookies \
firefox.crash_reports \
firefox.dom \
firefox.download_history \
firefox.forms \
firefox.passwords \
firefox.session_restore \
firefox.site_preferences \
firefox.url_history \
firefox.vacuum \
flash.cache \
flash.cookies \
gedit.recent_documents \
gftp.cache \
gftp.logs \
gimp.tmp \
gl-117.debug_logs \
gnome.run \
gnome.search_history \
google_chrome.cache \
google_chrome.cookies \
google_chrome.dom \
google_chrome.form_history \
google_chrome.history \
google_chrome.passwords \
google_chrome.search_engines \
google_chrome.session \
google_chrome.vacuum \
google_earth.temporary_files \
google_toolbar.search_history \
gpodder.cache \
gpodder.vacuum \
gwenview.recent_documents \
hippo_opensim_viewer.cache \
hippo_opensim_viewer.logs \
internet_explorer.cookies \
internet_explorer.forms \
internet_explorer.history \
internet_explorer.temporary_files \
java.cache \
kde.cache \
kde.recent_documents \
kde.tmp \
konqueror.cookies \
konqueror.current_session \
konqueror.url_history \
libreoffice.cache \
libreoffice.history \
liferea.cache \
liferea.cookies \
liferea.vacuum \
links2.history \
microsoft_office.debug_logs \
microsoft_office.mru \
midnightcommander.history \
miro.cache \
miro.logs \
nautilus.history \
nexuiz.cache \
octave.history \
openofficeorg.cache \
openofficeorg.recent_documents \
opera.cache \
opera.cookies \
opera.current_session \
opera.dom \
opera.download_history \
opera.search_history \
opera.url_history \
paint.mru \
realplayer.cookies \
realplayer.history \
realplayer.logs \
recoll.index \
rhythmbox.cache \
safari.cache \
safari.cookies \
safari.history \
safari.vacuum \
screenlets.logs \
seamonkey.cache \
seamonkey.chat_logs \
seamonkey.cookies \
seamonkey.download_history \
seamonkey.history \
secondlife_viewer.Cache \
secondlife_viewer.Logs \
silverlight.cookies \
skype.chat_logs \
sqlite3.history \
system.cache \
system.clipboard \
system.custom \
system.desktop_entry \
system.free_disk_space \
system.localizations \
system.memory \
system.recent_documents \
system.rotated_logs \
system.tmp \
system.trash \
teamviewer.logs \
teamviewer.mru \
thunderbird.cache \
thunderbird.cookies \
thunderbird.index \
thunderbird.passwords \
thunderbird.vacuum \
tortoisesvn.history \
tremulous.cache \
vlc.mru \
vuze.backup_files \
vuze.cache \
vuze.logs \
vuze.tmp \
warzone2100.logs \
winamp.mru \
windows_defender.history \
windows_explorer.mru \
windows_explorer.recent_documents \
windows_explorer.run \
windows_explorer.search_history \
windows_explorer.thumbnails \
windows_media_player.mru \
wine.tmp \
winetricks.temporary_files \
winrar.mru \
winzip.mru \
wordpad.mru \
x11.debug_logs \
xchat.logs \
xine.cache \
yahoo_messenger.cache \
yahoo_messenger.chat_logs \
yahoo_messenger.logs \
yum.clean_all \
yum.vacuum
